### ISSUE TITLE
[Bug] Announcements do not work

### ISSUE THREAD

**Issue by AmirKing2** [Solar-Tweaks/LunarSocket#12]
Right as I type boardcast LOL or something this shows up and then the lunarsocket crashes.

C:\Users\amirKing0\LunarSocket\dist\commands\broadcast.js:10
    for (const match of matches)
                        ^

TypeError: matches is not iterable
    at Command.handler (C:\Users\amirKing0\LunarSocket\dist\commands\broadcast.js:10:25)
    at Command.trigger (C:\Users\amirKing0\LunarSocket\dist\commands\Command.js:12:14)
    at CommandHandler.handle (C:\Users\amirKing0\LunarSocket\dist\commands\CommandHandler.js:27:17)
    at Object.default_1 [as default] (C:\Users\amirKing0\LunarSocket\dist\player\events\incoming\consoleMessage.js:6:27)    at IncomingPacketHandler.<anonymous> (C:\Users\amirKing0\LunarSocket\dist\player\Player.js:110:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by jhol3y** [comment]
it got fixed?
