### ISSUE TITLE
Cannot read properties of undefined (reading 'secure')

### ISSUE THREAD

**Issue by byemotivation** [Solar-Tweaks/LunarSocket#14]
TypeError: Cannot read properties of undefined (reading 'secure')
    at Object.<anonymous> (D:\LunarSocket\dist\index.js:18:19)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

**Comment by BoxCodingThings** [comment]
same issueTypeError: Cannot read properties of undefined (reading 'secure')
    at Object.<anonymous> (C:\Users\User\LunarSocket\dist\index.js:18:19)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

**Comment by Zone-Infinity** [comment]
Update your [config.json](https://github.com/Solar-Tweaks/LunarSocket/blob/main/config.example.json)

**Comment by BoxCodingThings** [comment]
Do you know where the key and cert is?

**Comment by byemotivation** [comment]
> Update your [config.json](https://github.com/Solar-Tweaks/LunarSocket/blob/main/config.example.json)

issue continued

**Comment by byemotivation** [comment]
> 

what exactly do i edit

**Comment by jhol3y** [comment]
i got it too when i type npm start
