### ISSUE TITLE
Broadcast message with colors.

### ISSUE THREAD

**Issue by Zone-Infinity** [Solar-Tweaks/LunarSocket#6]
How can we send colored broadcast message with `&`?

**Comment by RatchanonDev** [comment]
§ work as color code in the config welcome message.
We couldn't use § in the Console so I think we need a way to translate & to §.

**Comment by Zone-Infinity** [comment]
This could work `message.replace(/&([0123456789AaBbCcDdEeFfKkLlMmNnOoRr])/g, '§$1')` ? I guess.

**Comment by RichardDorian** [comment]
You can now add colored message with the broadcast command, same syntax as Minecraft, just use `&` instead of `§`.
Thanks @Zone-Infinity for the regex I totally didn't steal.

**Comment by Zone-Infinity** [comment]
I am getting error when i broadcast

TypeError: matches is not iterable
    at Command.handler (/root/LunarSocket/dist/commands/broadcast.js:10:25)
    at Command.trigger (/root/LunarSocket/dist/commands/Command.js:12:14)
    at CommandHandler.handle (/root/LunarSocket/dist/commands/CommandHandler.js:28:17)
    at Object.default_1 [as default] (/root/LunarSocket/dist/player/events/incoming/consoleMessage.js:6:27)
    at IncomingPacketHandler.<anonymous> (/root/LunarSocket/dist/player/Player.js:111:36)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Zone-Infinity** [comment]
@RichardDorian
